// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attack(arg1:string):Promise<void>;

export function Chat(arg1:string,arg2:string):Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function Drop(arg1:string):Promise<void>;

export function GetUsername():Promise<string>;

export function Group(arg1:string,arg2:string):Promise<void>;

export function Inventory():Promise<void>;

export function IsConnected():Promise<boolean>;

export function Look():Promise<void>;

export function Move(arg1:string):Promise<void>;

export function Quest(arg1:string):Promise<void>;

export function Quests():Promise<void>;

export function SendCommand(arg1:string):Promise<void>;

export function Status():Promise<void>;

export function Take(arg1:string):Promise<void>;

export function Talk(arg1:string):Promise<void>;

export function Who():Promise<void>;
