// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attack(arg1) {
  return window['go']['main']['App']['Attack'](arg1);
}

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Drop(arg1) {
  return window['go']['main']['App']['Drop'](arg1);
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function Group(arg1, arg2) {
  return window['go']['main']['App']['Group'](arg1, arg2);
}

export function Inventory() {
  return window['go']['main']['App']['Inventory']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Look() {
  return window['go']['main']['App']['Look']();
}

export function Move(arg1) {
  return window['go']['main']['App']['Move'](arg1);
}

export function Quest(arg1) {
  return window['go']['main']['App']['Quest'](arg1);
}

export function Quests() {
  return window['go']['main']['App']['Quests']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Take(arg1) {
  return window['go']['main']['App']['Take'](arg1);
}

export function Talk(arg1) {
  return window['go']['main']['App']['Talk'](arg1);
}

export function Who() {
  return window['go']['main']['App']['Who']();
}
